name: Deploy Secure Education First service
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          capabilities: CAPABILITY_NAMED_IAM
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
           --template-file deploy/ecs-deploy.yml \
           --stack-name education-first-stack \
           --parameter-overrides \
             VpcId=my-vpc-id \
             PublicSubnet1=my-public-subnet-1 \
             PublicSubnet2=my-public-subnet-2 \
             SecurityGroupIds=my-security-group-ids \
             TaskCpu=256 \
             TaskMemory=512 \
           --capabilities CAPABILITY_NAMED_IAM